name: Deploy Documentation to Github Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Add .nojekyll file
        run: touch docs/build/html/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: docs/build/html
